//Types PRODUCT

export const product = {
    GET_PRODUCTS: 'GET_PRODUCTS',
    ADD_SELLING_PRODUCT: 'ADD_SELLING_PRODUCT',
    DELETE_SELLING_PRODUCT: 'DELETE_SELLING_PRODUCT',
    MODIFY_SELLING_PRODUCT: 'MODIFY_SELLING_PRODUCT',
    GET_SELLING_PRODUCT: 'GET_SELLING_PRODUCT',
    GET_BOUGHT_PRODUCT: 'GET_BOUGHT_PRODUCT',
    GET_SOLD_PRODUCT: 'GET_SOLD_PRODUCT'
}

//Types USER
export const user = {
    GET_USER_DATA: 'GET_USER_DATA',
    CLEAR_USER_DATA: 'CLEAR_USER_DATA'
}